version: '3.4'

services:
  splendidcrm6_docker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    image: ${DOCKER_REGISTRY-}splendidcrm6docker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - splendidcrm_db
  splendidcrm_db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: splendidcrm_db
    environment:
        SA_PASSWORD: "SplendidCRM2005"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
